// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPuowtKeOeZJ2Thka6eOcuWCeuLlBZJtE',
    appId: '1:445439455141:web:c5430964ab6d66488c824c',
    messagingSenderId: '445439455141',
    projectId: 'milow-for-drivers',
    authDomain: 'milow-for-drivers.firebaseapp.com',
    storageBucket: 'milow-for-drivers.firebasestorage.app',
    measurementId: 'G-7R10GWBJ6D',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAChWGq81iVnGBfdo7bcPMbobIg4gzsHsM',
    appId: '1:445439455141:ios:1da57ad31181a3b98c824c',
    messagingSenderId: '445439455141',
    projectId: 'milow-for-drivers',
    storageBucket: 'milow-for-drivers.firebasestorage.app',
    iosBundleId: 'com.milow.admin.admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPuowtKeOeZJ2Thka6eOcuWCeuLlBZJtE',
    appId: '1:445439455141:web:80d27c00b7f4123e8c824c',
    messagingSenderId: '445439455141',
    projectId: 'milow-for-drivers',
    authDomain: 'milow-for-drivers.firebaseapp.com',
    storageBucket: 'milow-for-drivers.firebasestorage.app',
    measurementId: 'G-4M51D3PX54',
  );

}