default_platform(:android)

platform :android do
  desc "Upload metadata to Play Store"
  lane :update_metadata do
    upload_to_play_store(
      skip_upload_apk: true,
      skip_upload_aab: true,
      skip_upload_metadata: false,
      skip_upload_changelogs: false,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      track: "alpha",
      json_key_data: ENV["ANDROID_SERVICE_ACCOUNT_JSON"]
    )
  end
end
