-- Optimization: Add missing indexes on Foreign Keys to improve JOIN performance
-- Auto-generated by Antigravity based on Supabase Postgres Best Practices

-- 1. auth.mfa_challenges(factor_id)
create index concurrently if not exists mfa_challenges_factor_id_idx on auth.mfa_challenges(factor_id);

-- 2. auth.saml_relay_states(flow_state_id)
create index concurrently if not exists saml_relay_states_flow_state_id_idx on auth.saml_relay_states(flow_state_id);

-- 3. storage.s3_multipart_uploads_parts(upload_id)
create index concurrently if not exists s3_multipart_uploads_parts_upload_id_idx on storage.s3_multipart_uploads_parts(upload_id);

-- 4. auth.oauth_authorizations(client_id)
create index concurrently if not exists oauth_authorizations_client_id_idx on auth.oauth_authorizations(client_id);

-- 5. auth.oauth_authorizations(user_id)
create index concurrently if not exists oauth_authorizations_user_id_idx on auth.oauth_authorizations(user_id);

-- 6. storage.s3_multipart_uploads_parts(bucket_id)
create index concurrently if not exists s3_multipart_uploads_parts_bucket_id_idx on storage.s3_multipart_uploads_parts(bucket_id);

-- 7. fleet_assignments(assigned_by)
create index concurrently if not exists fleet_assignments_assigned_by_idx on public.fleet_assignments(assigned_by);

-- 8. audit_logs(changed_by)
create index concurrently if not exists audit_logs_changed_by_idx on public.audit_logs(changed_by);

-- 9. driver_profiles(company_id)
create index concurrently if not exists driver_profiles_company_id_idx on public.driver_profiles(company_id);

-- 10. company_staff_profiles(company_id)
create index concurrently if not exists company_staff_profiles_company_id_idx on public.company_staff_profiles(company_id);

-- 11. contacts(customer_id)
create index concurrently if not exists contacts_customer_id_idx on public.contacts(customer_id);

-- 12. locations(customer_id)
create index concurrently if not exists locations_customer_id_idx on public.locations(customer_id);

-- 13. documents(customer_id)
create index concurrently if not exists documents_customer_id_idx on public.documents(customer_id);

-- 14. tags(customer_id)
create index concurrently if not exists tags_customer_id_idx on public.tags(customer_id);

-- 15. customer_commissioned_users(customer_id)
create index concurrently if not exists customer_commissioned_users_customer_id_idx on public.customer_commissioned_users(customer_id);

-- 16. customer_commissioned_users(user_id)
create index concurrently if not exists customer_commissioned_users_user_id_idx on public.customer_commissioned_users(user_id);

-- 17. user_credentials(created_by)
create index concurrently if not exists user_credentials_created_by_idx on public.user_credentials(created_by);

-- 18. loads(assigned_trailer_id)
create index concurrently if not exists loads_assigned_trailer_id_idx on public.loads(assigned_trailer_id);

-- 19. loads(company_id)
create index concurrently if not exists loads_company_id_idx on public.loads(company_id);

-- 20. invoices(company_id)
create index concurrently if not exists invoices_company_id_idx on public.invoices(company_id);

-- 21. quotes(company_id)
create index concurrently if not exists quotes_company_id_idx on public.quotes(company_id);

-- 22. contacts(company_id)
create index concurrently if not exists contacts_company_id_idx on public.contacts(company_id);

-- 23. documents(company_id)
create index concurrently if not exists documents_company_id_idx on public.documents(company_id);

-- 24. settlement_items(company_id)
create index concurrently if not exists settlement_items_company_id_idx on public.settlement_items(company_id);

-- 25. driver_settlements(company_id)
create index concurrently if not exists driver_settlements_company_id_idx on public.driver_settlements(company_id);

-- 26. driver_expenses(trip_id)
create index concurrently if not exists driver_expenses_trip_id_idx on public.driver_expenses(trip_id);

-- 27. maintenance_records(created_by)
create index concurrently if not exists maintenance_records_created_by_idx on public.maintenance_records(created_by);

-- 28. dvir_reports(driver_id)
create index concurrently if not exists dvir_reports_driver_id_idx on public.dvir_reports(driver_id);

-- 29. stops(load_id)
create index concurrently if not exists stops_load_id_idx on public.stops(load_id);

-- 30. accessorial_charges(load_id)
create index concurrently if not exists accessorial_charges_load_id_idx on public.accessorial_charges(load_id);
