-- Migration: Add address details to stops table
-- Created: 2026-01-24

ALTER TABLE stops ADD COLUMN IF NOT EXISTS company_name TEXT;
ALTER TABLE stops ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE stops ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE stops ADD COLUMN IF NOT EXISTS state TEXT;
ALTER TABLE stops ADD COLUMN IF NOT EXISTS zip_code TEXT;
ALTER TABLE stops ADD COLUMN IF NOT EXISTS contact_name TEXT;
ALTER TABLE stops ADD COLUMN IF NOT EXISTS contact_phone TEXT;
ALTER TABLE stops ADD COLUMN IF NOT EXISTS contact_fax TEXT;
